# Copyright (c) Zhifan Chen
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
---
name: Documentation Release

'on':
  push:
    branches:
      - master

jobs:
  test:
    uses: ./.github/workflows/doc-test.yml
    secrets: inherit

  deploy-documentation:
    name: Deploy Documentation to GitHub Pages
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/lexical-website
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies, including the root ones
        run: |
          cd ../../
          npm install
          cd packages/lexical-website
          npm install
      - name: Build website
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/lexical-website/build
          user_name: fannifanni
          user_email: 3544242744@qq.com
