# Copyright (c) Zhifan Chen
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
---
    name: Documentation Test
    
    'on':
      workflow_call:
      pull_request:
        types: [opened, synchronize, reopened]
    
    jobs:
      test:
        name: Test Website Build
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: packages/lexical-website
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-node@v3
            with:
              node-version: 16
          - name: Install dependencies, including the root ones
            run: |
              cd ../../
              npm install
              cd packages/lexical-website
              npm install
          - name: Build website
            run: npm run build
